const GO_BACK = 'GO_BACK';
const GO_FORWARD = 'GO_FORWARD';
const ADD_NODE = 'ADD_NODE';
const UPDATE_NODE = 'UPDATE_NODE';
const UPDATE_SELECT_NODES = 'UPDATE_SELECT_NODES';

export default {
  GO_BACK,
  GO_FORWARD,
  ADD_NODE,
  UPDATE_NODE,
  UPDATE_SELECT_NODES
};
